name: Test GitHub Token

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test-token:
    runs-on: ubuntu-latest

    steps:
      - name: Test GitHub Token
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.MY_NEW_GITHUB_TOKEN }}
          script: |
            const result = await github.request('GET /repos/:owner/:repo', {
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(result);
