name: Workflow 3

on:
  push:
    branches:
      - develop
  workflow_dispatch: # Add this trigger to allow manual workflow runs

jobs:
  rerun-workflow1:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Extract Branch Name
        uses: actions/checkout@v2

      - name: Get Branch Name
        id: extract_branch
        run: echo ::set-output name=branch_name::$(git rev-parse --abbrev-ref HEAD)

      - name: Rerun Workflow 1
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.MY_NEW_GITHUB_TOKEN }}
          script: |
            try {
              const branchName = '${{ steps.extract_branch.outputs.branch_name }}';
              const response = await github.request('GET /repos/:owner/:repo/actions/workflows', {
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              const workflows = response.data.workflows;
              const workflow = workflows.find(w => w.name === 'Check Commits');
              if (workflow) {
                const { data } = await github.actions.reRunWorkflow({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: workflow.latest_run.id
                });
                console.log(`Workflow workflow1.yml rerun triggered for branch ${branchName}`);
              } else {
                throw new Error('Workflow workflow1.yml not found.');
              }
            } catch (error) {
              console.error('Error:', error.message);
              core.setFailed(error.message);
            }
