name: Check Commits

on:
  pull_request:
    branches:
      - staging

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch develop branch
        run: git fetch origin develop

      - name: Find merge base
        id: merge-base
        run: echo "::set-output name=base::$(git merge-base HEAD origin/develop)"

      - name: Check commits
        run: |
          # Check if all commits from feature branch are in develop
          if [[ -n "$(git diff --name-only ${{ steps.merge-base.outputs.base }} HEAD)" ]]; then
            echo "Not all commits from the feature branch are in develop."
            exit 1
          fi

