name: Merge Pull Request Workflow

on:
  pull_request_review:
    branches:
      - staging
    types: [submitted]

jobs:
  merge_and_test:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'staging'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch develop branch
        run: git fetch origin develop

      - name: Check commits
        run: |
          # Check if all commits from feature branch are in develop
          git fetch origin ${{ github.head_ref }}
          commits_not_in_develop=$(git rev-list --count origin/${{ github.head_ref }} ^origin/develop)
          if [ $commits_not_in_develop -eq 0 ]; then
            echo "All commits from the feature branch are in develop."
          else
            echo "Not all commits from the feature branch are in develop."
            exit 1
          fi

      - name: Fail on Check commits failure
        if: failure()
        run: exit 1

#      # Perform merge if tests pass
#      - name: Merge to staging
#        uses: pullreminders/merge-action@v2
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          merge_method: squash
#          base: staging
