name: Workflow 5

on:
  push:
    branches:
      - develop

jobs:
  rerun-workflow1:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Branch Name
        uses: actions/checkout@v2

      - name: Get Branch Name
        id: extract_branch
        run: echo ::set-output name=branch_name::$(git rev-parse --abbrev-ref HEAD)

      - name: Debug Logging
        run: |
          echo "Owner: ${{ github.repository_owner }}"
          echo "Repo: ${{ github.event.repository.name }}"
          echo "Branch: ${{ steps.extract_branch.outputs.branch_name }}"

      - name: Rerun Workflow 1
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.MY_NEW_GITHUB_TOKEN }}
          script: |
            const branchName = '${{ steps.extract_branch.outputs.branch_name }}';
            console.log('branchName', branchName);

            async function run() {
              const { data: { workflows } } = await github.rest.actions.listRepoWorkflows({
                owner: '${{ github.repository_owner }}',
                repo: '${{ github.event.repository.name }}'
              });
              console.log('workflows', workflows);
              const workflowName = 'check-commits.yml'; // Adjust the workflow file name if necessary
              const workflow = workflows.find(w => w.path === `.github/workflows/${workflowName}`);
              if (workflow) {
                if (workflow.latest_run) {
                  await github.rest.actions.reRunWorkflow({
                    owner: '${{ github.repository_owner }}',
                    repo: '${{ github.event.repository.name }}',
                    run_id: workflow.latest_run.id,
                    workflow_id: workflow.id,
                    ref: `refs/heads/${branchName}`
                  });
                  console.log(`Workflow ${workflowName} rerun triggered for branch ${branchName}`);
                } else {
                  console.log(`No previous runs found for workflow ${workflowName}`);
                }
              } else {
                console.log(`Workflow ${workflowName} not found.`);
              }
            }

            run();
